name: test

on:
  push:
    paths:
      - 'Image2Display/**'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - 'Image2Display/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: environment prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          sudo apt-get update
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 9.0
      - name: test
        run: |
          cd Image2Display
          dotnet test
